/**
 * @brief
 *  Default config values to set
 *  for the firs time in the
 *  Data Base, this values matches
 *  the default Device JSON in utils,
 *  so if you modify a value here, make sure
 *  that matches with the utils JSON, and 
 *  if it does not, modify utils also.
 */


const CONFIG = {//DEFAULT VALUES (NEED TO ADD DEVICE ID ONLY) : JSON FOR DATA BASE TABLE
  
     command :     { configId:1,  value:"NAN",  pending:1 }, //comand
     reportType:   { configId:2,  value:"HOUR", pending:1 }, //type HOUR or INT
     timeHour:     { configId:3,  value:2,      pending:1 }, // time HOUR
     timeMin:      { configId:4,  value:1440,   pending:1 }, //time MINUTES
     samplingTime: { configId:5,  value:10,     pending:1 }, // sampling Time
     maxSamples:   { configId:6,  value:5,      pending:1 }, // max average samples
     therm1:       { configId:7,  value:0,      pending:1 }, //thermistors
     therm2:       { configId:8,  value:0,      pending:1 },
     therm3:       { configId:9,  value:0,      pending:1 },
     therm4:       { configId:10, value:0,      pending:1 },
     gpioFilter0:  { configId:11, value:1000,   pending:1 }, //GPIO filter millis
     gpioFilter1:  { configId:12, value:1000,   pending:1 },
     gpioFilter2:  { configId:13, value:1000,   pending:1 },
     gpioFilter3:  { configId:14, value:1000,   pending:1 },
     gpioFilter4:  { configId:15, value:1000,   pending:1 },
     gpioFilter5:  { configId:16, value:1000,   pending:1 },
     gpioFilter6:  { configId:17, value:1000,   pending:1 },
     gpioFilter7:  { configId:18, value:1000,   pending:1 },
     gpioFilter8:  { configId:19, value:1000,   pending:1 },
     gpioFilter9:  { configId:20, value:1000,   pending:1 },
     gpioFilter10: { configId:21, value:1000,   pending:1 },
     gpioFilter11: { configId:22, value:1000,   pending:1 },
     gpioFilter12: { configId:23, value:1000,   pending:1 },
     gpioFilter13: { configId:24, value:1000,   pending:1 },
     gpioFilter14: { configId:25, value:1000,   pending:1 },
     gpioFilter15: { configId:26, value:1000,   pending:1 },
     lte:          { configId:27, value:0,      pending:1 }, //LTE FLAG
     gps:          { configId:28, value:0,      pending:1 }  //GPS FLAG
   
};

const ADV_CONFIG = {

     KA:      { configId:1, value:0,   pending:1 },
     KA_GPS:  { configId:2, value:0,   pending:1 },
     GPS_LOG: { configId:3, value:0,   pending:1 },
     TIME:    { configId:4, value:0,   pending:1 },
     //KEY is autogenerated In script 
     //DAY is autogenerated In script 
};

const LIGHT_MOD_CONFIG = {
     module1 :{
          //deviceId must be assigned in script
          modulePos: 1,
          enable: 0,
          moduleAddress: 11, //will depend on dip switch <----- MUST UPDATE WHEN TESTING...
          pending: 1
     },
     module2 :{
          //deviceId must be assigned in script
          modulePos: 2,
          enable: 0,
          moduleAddress: 22, //will depend on dip switch <----- MUST UPDATE WHEN TESTING...
          pending: 1
     },
     module3 :{
          //deviceId must be assigned in script
          modulePos: 3,
          enable: 0,
          moduleAddress: 33, //will depend on dip switch <----- MUST UPDATE WHEN TESTING...
          pending: 1
     },
     module4 :{
          //deviceId must be assigned in script
          modulePos: 4,
          enable: 0,
          moduleAddress: 44, //will depend on dip switch <----- MUST UPDATE WHEN TESTING...
          pending: 1
     }
};

const LIGHT_SENS_CONFIG = {
     //rowId AUTO GENERATED IN MYSQL
     //moduleCode must be set in script
     sensor1:  { sensor:1, treshold:10, edge:1, filter:1000, statusActive:1 },
     sensor2:  { sensor:2, treshold:10, edge:1, filter:1000, statusActive:0 },
     sensor3:  { sensor:3, treshold:10, edge:1, filter:1000, statusActive:0 }

}

const MONITOR_CONF = {
     //deviceId must be assigned in script
     defrosting_th : { configId:1,  value:-1,      pending:1 },
     defrosting_T :  { configId:2,  value:300000,    pending:1 },
     defrosting_S :  { configId:3,  value:300000,       pending:1 },
     compD_high :    { configId:4,  value:60,      pending:1 },
     compD_low :     { configId:5,  value:5,       pending:1 },
     compD_high_T :  { configId:6,  value:600000,  pending:1 },
     compD_low_T :   { configId:7,  value:600000,  pending:1 },
     compD_OK_T :    { configId:8,  value:300000,     pending:1 },
     compD_stop_H :  { configId:9,  value:0,       pending:1 },
     compD_stop_L :  { configId:10, value:0,       pending:1 },
     compS_high :    { configId:11, value:60,      pending:1 },
     compS_low :     { configId:12, value:5,       pending:1 },
     compS_high_T :  { configId:13, value:600000,  pending:1 },
     compS_low_T :   { configId:14, value:600000,  pending:1 },
     compS_OK_T :    { configId:15, value:300000,     pending:1 },
     compS_stop_H :  { configId:16, value:0,       pending:1 },
     compS_stop_L :  { configId:17, value:0,       pending:1 },
     door_opn_T :    { configId:18, value:60000,  pending:1 },
     door_cls_T :    { configId:19, value:60000,  pending:1 },
     main_pow_ON :   { configId:20, value:0,       pending:1 },
     main_pow_OFF:   { configId:21, value:0,       pending:1 },
     cedis_pow_ON :  { configId:22, value:0,       pending:1 },
     cedis_pow_OFF:  { configId:23, value:0,       pending:1 },
     comp_diff_th:   { configId:24, value:5,       pending:1 },
     comp_diff_T:    { configId:25, value:300000,    pending:1 },
     comp_diff_stop: { configId:26, value:0,       pending:1 },
     powerB_full:    { configId:27, value:4.0,   pending:1 },    
     powerB_F_Up_T:  { configId:28, value:5,     pending:1 },
     PB_Full_Down_T: { configId:29, value:5,     pending:1 },
     powerB_empty:   { configId:30, value:3.4,     pending:1 },
     PB_E_Up_T:      { configId:31, value:5,     pending:1 },
     PB_E_Down_T:    { configId:32, value:5,     pending:1 },
     powerBank_diff: { configId:33, value:0.5,     pending:1 },
     comp_ON:        { configId:34, value:259200,     pending:1 }

}

const LIVE_EVENT = {
     //deviceId must be assigned in script
     Defrost :                   { eventId:1,  value:0,  pending:1 },
     Box_temp_stable :           { eventId:2,  value:0,  pending:1 },
     High_temp_suction :         { eventId:3,  value:0,  pending:1 },
     Low_temp_suction :          { eventId:4,  value:0,  pending:1 },
     Suction_temp_stable :       { eventId:5,  value:0,  pending:1 },
     High_temp_download :        { eventId:6,  value:1,  pending:1 },
     Low_temp_download :         { eventId:7,  value:0,  pending:1 },
     Download_temp_stable :      { eventId:8,  value:0,  pending:1 },
     Open_door_time_treshold :   { eventId:9,  value:0,  pending:1 },
     Closed_door :               { eventId:10, value:0,  pending:1 },
     Battery_disconnected :      { eventId:11, value:0,  pending:1 },
     Battery_connected :         { eventId:12, value:0,  pending:1 },
     External_source_NC :        { eventId:13, value:0,  pending:1 },
     External_source_connected : { eventId:14, value:0,  pending:1 },
     Dangerous_temps_diff :      { eventId:15, value:0,  pending:1 },
     Power_Bank_F :              { eventId:16, value:0,  pending:1 },
     Power_Bank_N_F :            { eventId:17, value:1,  pending:1 }, 
     Power_Bank_E :              { eventId:18, value:0,  pending:1 },
     Power_Bank_N_E :            { eventId:19, value:1,  pending:1 }
     // Power_Bank_v_diff :         { eventId:20, value:0,  pending:1 },
     // Comp_OFF_cont :             { eventId:21, value:0,  pending:1 },
     // Comp_ON_after_long_period : { eventId:22, value:0,  pending:1 }
}

module.exports = {
     CONFIG,
     ADV_CONFIG,
     LIGHT_MOD_CONFIG,
     LIGHT_SENS_CONFIG,
     MONITOR_CONF,
     LIVE_EVENT
};